"""
CRITICAL FINDINGS: C2 Chemistry and Suprathermal H Atoms

Based on analysis of the model and user's experimental information about
suprathermal H atoms at the cathode sheath (100 eV and 17.5 eV).
"""

print("="*80)
print("C2 CHEMISTRY WITH SUPRATHERMAL H ATOMS - ANALYSIS")
print("="*80)

print("\n" + "="*80)
print("1. SUPRATHERMAL H ATOM ENERGIES")
print("="*80)

print("\nExperimental conditions (from user):")
print("  - H atoms with ~100 eV at cathode sheath")
print("  - H atoms with ~17.5 eV at cathode sheath")
print("  - Thermal H atoms at Tgas = 570 K ~ 0.05 eV")
print()

print("Energy requirements:")
print("  - H + C2H2 → C2 + H2 + H barrier: ~5.2 eV (603 kJ/mol)")
print("  - C2 + H → CH + C barrier: ~0-0.5 eV (near thermoneutral)")
print()

print("Can reactions occur?")
print("  ✓ 100 eV H atoms  >> 5.2 eV barrier → YES, easily")
print("  ✓ 17.5 eV H atoms >> 5.2 eV barrier → YES")
print("  ✗ 0.05 eV thermal >> 5.2 eV barrier → NO")
print()

print("="*80)
print("2. IMPLICATIONS FOR C2 PRODUCTION")
print("="*80)

print("\nH + C2H2 → C2 + H2 + H (95% of C2 production):")
print("  - Requires hot H atoms (>5 eV)")
print("  - Driven by cathode-accelerated H from sheath")
print("  - NOT a thermal reaction at 570K")
print("  - Model rate k=1e-11 cm³/s likely represents:")
print("    * Effective rate averaged over H energy distribution")
print("    * Or empirical fit to high-T combustion data")
print()

print("Key question:")
print("  What fraction of H atoms are suprathermal vs thermal?")
print("  - If small fraction: bulk H is thermal (0.05 eV)")
print("  - If large fraction: model might be reasonable")
print()

print("="*80)
print("3. IMPLICATIONS FOR C2 DESTRUCTION")
print("="*80)

print("\nC2 + H → CH + C (93% of C2 destruction):")
print("  - Nearly thermoneutral (small or no barrier)")
print("  - Should work with BOTH hot and thermal H atoms")
print("  - Model k=9.6e-11 cm³/s is for thermal H")
print()

print("CRITICAL QUESTION:")
print("  Does the rate increase for hot H atoms?")
print("  - If YES: Hot H destroys C2 faster → even worse balance")
print("  - If NO:  Hot H creates C2, thermal H destroys it")
print()

print("Energy dependence scenarios:")
print()
print("Scenario A: C2+H rate is energy-independent")
print("  - Hot H creates C2 via H+C2H2")
print("  - Thermal H destroys C2 via C2+H")
print("  - Different H populations → might help balance")
print()
print("Scenario B: C2+H rate increases with H energy")
print("  - Hot H both creates AND destroys C2")
print("  - Destruction enhanced for hot H")
print("  - Balance even tighter → worse!")
print()

print("="*80)
print("4. SPATIAL CONSIDERATIONS")
print("="*80)

print("\nCathode sheath region:")
print("  - High E-field accelerates ions → H+ → fast H")
print("  - H+ + e → H* (suprathermal)")
print("  - Fast H can drive H + C2H2 → C2")
print("  - C2 produced near cathode")
print()

print("Bulk plasma region:")
print("  - Thermal H atoms (570K ~ 0.05 eV)")
print("  - C2 + H → CH + C can occur")
print("  - C2 destroyed in bulk")
print()

print("Your measurement location:")
print("  - Sheath edge (where ne measured)")
print("  - Transition region: some hot H, some thermal H")
print("  - C2 density reflects balance at this location")
print()

print("="*80)
print("5. MODEL LIMITATIONS")
print("="*80)

print("\nCurrent 0D model assumes:")
print("  ✗ All H atoms have same temperature (Maxwell-Boltzmann)")
print("  ✗ Single rate constant for all H atoms")
print("  ✗ Well-mixed (no spatial variation)")
print()

print("Reality:")
print("  ✓ Non-Maxwellian H distribution (thermal + suprathermal)")
print("  ✓ Energy-dependent rate constants")
print("  ✓ Spatial gradients (sheath vs bulk)")
print()

print("To properly model this, you would need:")
print("  1. H energy distribution f(E)")
print("  2. Energy-dependent rate constants k(E)")
print("  3. Spatial resolution (1D or 2D)")
print()

print("="*80)
print("6. LITERATURE FINDINGS")
print("="*80)

print("\nC2 formation mechanisms in hydrocarbon plasmas:")
print("  - Low-T plasma (DBD): Radical recombination → C2Hx")
print("  - High-T plasma (arc): Thermal decomposition → C2H2 → C2")
print("  - Cathode region: Sputtering + hot atom chemistry")
print()

print("C2 detection methods:")
print("  - LIF on Swan bands d-a (used by user)")
print("  - Sensitive to vibrational temperature Tv")
print("  - C2 often vibrationally excited in plasmas")
print()

print("Hot atom chemistry:")
print("  - Well-studied in nuclear recoil chemistry")
print("  - Less studied in plasma context")
print("  - Energy-dependent cross sections exist for some reactions")
print()

print("="*80)
print("7. RECOMMENDATIONS")
print("="*80)

print("\nImmediate actions:")
print()
print("1. Characterize H energy distribution")
print("   - What fraction of H is suprathermal?")
print("   - Measure or estimate from sheath physics")
print()

print("2. Check Baulch et al. (2005) (user will do)")
print("   - Temperature range for H + C2H2 → C2 rate")
print("   - Is it valid at 570K?")
print("   - Or only for high-T combustion (>1500K)?")
print()

print("3. Literature search for energy-dependent rates")
print("   - H + C2H2 → C2 + H2 + H: k(E)")
print("   - C2 + H → CH + C: k(E)")
print("   - May need molecular dynamics or RRKM calculations")
print()

print("4. Consider two-temperature H model")
print("   - Thermal H: T = 570K, density n_H_thermal")
print("   - Hot H: <E> = 10-100 eV, density n_H_hot")
print("   - Different rate constants for each")
print()

print("5. Re-examine C2 vibrational excitation")
print("   - C2 from H + C2H2 likely vibrationally hot")
print("   - C2(v) + H rate different from C2(v=0) + H")
print("   - This is your original hypothesis!")
print()

print("="*80)
print("8. TESTABLE PREDICTIONS")
print("="*80)

print("\nIf hot H drives H + C2H2 → C2:")
print("  ✓ C2 production should be enhanced near cathode")
print("  ✓ C2 density gradient: higher near cathode")
print("  ✓ C2 vibrational temperature Tv > Tgas")
print()

print("If thermal H dominates C2 + H → CH:")
print("  ✓ CH production distributed throughout plasma")
print("  ✓ CH/C2 ratio higher in bulk than near cathode")
print()

print("Can you test these with your 1D profiles?")
print("  - C2(r), CH(r), H(r) vs distance from cathode")
print("  - If C2 peaks near cathode → hot H production")
print("  - If CH peaks in bulk → thermal H destruction")
print()

print("="*80)
print("SUMMARY")
print("="*80)

print("\nKey insight:")
print("  The dominant C2 production reaction H + C2H2 → C2 + H2 + H")
print("  is thermochemically impossible for thermal H (570K)")
print("  BUT is easily driven by your suprathermal H (17.5-100 eV)!")
print()

print("This resolves the thermochemistry paradox:")
print("  ✓ Hot H creates C2 (can overcome 5.2 eV barrier)")
print("  ✓ Thermal H might destroy C2 (near-thermoneutral)")
print("  ✓ Different H populations → complex balance")
print()

print("Next steps:")
print("  1. User checks Baulch et al. for temperature range")
print("  2. Estimate hot vs thermal H fractions")
print("  3. Search for energy-dependent C2+H rate constants")
print("  4. Consider if vibrationally hot C2 is less reactive")
print()
print("This could explain everything!")
print("="*80)
